import { RHCA_CORE } from "./config.js";
import { getState, mutate, recordEvent, criterionQualityChecks } from "./state.js";
import { exportFramework } from "./services.js";

const esc = v => String(v ?? "").replace(/[&<>'"]/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const blankCriterion = () => ({ name:"New domain criterion", relationship:"A", definition:"", evidence:"", anchors:{1:"",2:"",3:""}, tags:"" });
const checks = c => { const q=criterionQualityChecks(c); return [q.specificName,q.rhcaMapping,q.observableDefinition,q.evidenceRule,q.distinctAnchors,q.failureTags]; };

export function renderFramework(root) {
  const s=getState(), fw=s.framework, i=Math.min(fw.activeCriterionIndex,fw.criteria.length-1), c=fw.criteria[i];
  const quality=checks(c), passed=quality.filter(Boolean).length;
  root.innerHTML=`<div class="page"><header class="page-header"><div><span class="eyebrow">Task 2 · domain framework building</span><h1>Customize a framework for your domain</h1><p>Describe a multi-turn AI use case in your own domain, then create at least 2 domain-specific criteria. Every criterion must meet all six requirements.</p></div><div class="header-actions"><button id="addCriterion" class="button secondary">+ Add criterion</button><button id="exportFramework" class="button secondary">Export</button><button id="completeFramework" class="button success">Complete task</button></div></header>
  <section class="card domain-scenario-card"><div class="section-title"><div><span class="eyebrow">Your domain scenario</span><h2>Describe one multi-turn AI use case</h2></div><span>Keep each response brief</span></div><div class="three-fields"><label>Domain<input id="scenarioDomain" value="${esc(s.domainScenario.domain)}" placeholder="e.g., healthcare administration"></label><label>User and goal<textarea id="scenarioUserGoal" placeholder="Who uses the AI, and what are they trying to do?">${esc(s.domainScenario.userAndGoal)}</textarea></label><label>Possible behavioral risk across turns<textarea id="scenarioRisk" placeholder="What might the AI forget, misunderstand, or explain inconsistently?">${esc(s.domainScenario.behavioralRisk)}</textarea></label></div><div class="scenario-detail-fields"><label>Important constraint<textarea id="scenarioConstraint" placeholder="What must the AI remember or continue following across turns?">${esc(s.domainScenario.importantConstraint)}</textarea></label><label>Expected interaction length<select id="scenarioLength"><option value="">Select a range</option>${["2–3 turns","4–6 turns","7–10 turns","More than 10 turns","Varies by case"].map(x=>`<option value="${x}" ${s.domainScenario.expectedInteractionLength===x?"selected":""}>${x}</option>`).join("")}</select></label></div></section>
  <div class="framework-shell"><aside class="framework-sidebar"><h2>Criteria (${fw.criteria.length})</h2><div class="criterion-list">${fw.criteria.map((x,n)=>{const q=criterionQualityChecks(x);return `<button class="criterion-tab ${n===i?"active":""}" data-criterion="${n}"><b>${esc(x.name)}</b><small>${x.relationship} · ${esc(RHCA_CORE[x.relationship].name)} · ${q.passedCount}/6</small></button>`;}).join("")}</div><div class="notice"><b>Task requirement:</b> create at least 2 criteria. Each criterion must pass all 6 checks.</div><div class="notice"><b>Stable core:</b> criteria may extend RHCA, but cannot rename or remove its four constructs.</div></aside>
  <section class="framework-editor"><div class="section-title"><h2>Criterion ${i+1}</h2><span><button id="duplicateCriterion" class="text-button">Duplicate</button> <button id="deleteCriterion" class="text-button">Delete</button></span></div><div class="two-fields"><label>Criterion name<input id="criterionName" value="${esc(c.name)}"></label><label>RHCA parent<select id="criterionRelationship">${Object.entries(RHCA_CORE).map(([k,d])=>`<option value="${k}" ${c.relationship===k?"selected":""}>${k} · ${esc(d.name)}</option>`).join("")}</select></label></div><label>Observable construct<textarea id="criterionDefinition">${esc(c.definition)}</textarea></label><label>Evidence rule<textarea id="criterionEvidence">${esc(c.evidence)}</textarea></label><h2>Anchored ratings</h2><div class="anchor-grid">${[1,2,3].map(n=>`<label><span class="score-box">${n}</span><textarea data-anchor="${n}">${esc(c.anchors[n])}</textarea></label>`).join("")}</div><label class="failure-tags-field">Domain failure tags<textarea id="criterionTags" rows="5" placeholder="Enter multiple tags separated by commas, e.g., oversimplification, missing prerequisite, unexplained jargon">${esc(c.tags)}</textarea><small>Add as many tags as needed. Separate tags with commas.</small></label></section>
  <aside class="quality-panel"><div class="quality-score"><span>Required criterion checks</span><b>${passed}/6</b><div class="progress-bar"><i style="width:${passed/6*100}%"></i></div></div><p class="quality-guide-note">Complete all six checks for every criterion before finishing the task.</p>${["Specific name","RHCA mapping","Observable definition","Evidence rule","Distinct anchors","Failure tags"].map((x,n)=>`<div class="quality-check ${quality[n]?"pass":"fail"}"><b>${quality[n]?"✓":"!"}</b><span>${x}</span></div>`).join("")}<div class="preview-card"><pre>${esc(JSON.stringify({criteria:fw.criteria.map(x=>({name:x.name,parent:x.relationship,checks:`${criterionQualityChecks(x).passedCount}/6`}))},null,2))}</pre></div></aside></div></div>`;
  bind(root,i);
}

function bind(root,i){
 const rerender=()=>renderFramework(root); const edit=(field,value)=>mutate(s=>{s.framework.criteria[i][field]=value;s.framework.status="draft";},"framework.criterion_edited",{index:i,field});
 [["scenarioDomain","domain"],["scenarioUserGoal","userAndGoal"],["scenarioConstraint","importantConstraint"],["scenarioRisk","behavioralRisk"]].forEach(([id,field])=>root.querySelector(`#${id}`).oninput=e=>mutate(s=>{s.domainScenario[field]=e.target.value;s.completed.framework=false;},"domain_scenario.edited",{field,length:e.target.value.length}));
 root.querySelector("#scenarioLength").onchange=e=>mutate(s=>{s.domainScenario.expectedInteractionLength=e.target.value;s.completed.framework=false;},"domain_scenario.edited",{field:"expectedInteractionLength",value:e.target.value});
 root.querySelectorAll("[data-criterion]").forEach(b=>b.onclick=()=>{mutate(s=>s.framework.activeCriterionIndex=Number(b.dataset.criterion),"framework.criterion_selected");rerender();});
 root.querySelector("#addCriterion").onclick=()=>{mutate(s=>{s.framework.criteria.push(blankCriterion());s.framework.activeCriterionIndex=s.framework.criteria.length-1;s.completed.framework=false;},"framework.criterion_added");rerender();};
 root.querySelector("#duplicateCriterion").onclick=()=>{mutate(s=>{const copy=structuredClone(s.framework.criteria[i]);copy.name+=` copy`;s.framework.criteria.splice(i+1,0,copy);s.framework.activeCriterionIndex=i+1;},"framework.criterion_duplicated");rerender();};
 root.querySelector("#deleteCriterion").onclick=()=>{if(getState().framework.criteria.length===1)return alert("A framework needs at least one criterion.");mutate(s=>{s.framework.criteria.splice(i,1);s.framework.activeCriterionIndex=Math.max(0,i-1);},"framework.criterion_deleted");rerender();};
 [["criterionName","name"],["criterionRelationship","relationship"],["criterionDefinition","definition"],["criterionEvidence","evidence"],["criterionTags","tags"]].forEach(([id,f])=>{root.querySelector(`#${id}`).onchange=e=>{edit(f,e.target.value);rerender();};});
 root.querySelectorAll("[data-anchor]").forEach(a=>a.onchange=e=>{mutate(s=>s.framework.criteria[i].anchors[e.target.dataset.anchor]=e.target.value,"framework.anchor_edited");rerender();});
 root.querySelector("#exportFramework").onclick=exportFramework;
 root.querySelector("#completeFramework").onclick=()=>{const current=getState(),ds=current.domainScenario;if(!ds.domain.trim()||!ds.userAndGoal.trim()||!ds.importantConstraint.trim()||!ds.behavioralRisk.trim()||!ds.expectedInteractionLength)return alert("Complete all five domain scenario fields before finishing the task.");if(current.framework.criteria.length<2)return alert("Please create at least two domain-specific criteria before completing the task.");const incomplete=current.framework.criteria.map((criterion,index)=>({index,quality:criterionQualityChecks(criterion)})).filter(item=>item.quality.passedCount<item.quality.totalCount);if(incomplete.length)return alert(`Complete all 6 required checks for ${incomplete.map(item=>`Criterion ${item.index+1} (${item.quality.passedCount}/6)`).join(", ")}.`);mutate(s=>{s.framework.status="ready for pilot";s.framework.domain=s.domainScenario.domain;s.framework.domainScenario=structuredClone(s.domainScenario);s.participantProfile.domain=s.domainScenario.domain;s.completed.framework=true;},"task.framework_completed",{criteria:current.framework.criteria.length,qualityChecks:current.framework.criteria.map(criterion=>criterionQualityChecks(criterion)),domain:current.domainScenario.domain,domainScenario:structuredClone(current.domainScenario)});rerender();};
 recordEvent("view.framework_opened",{criterionIndex:i});
}
