const sessions=[
{id:"EDU-184",task:"Debug a loop in a music-coding project",priority:"High",signal:"Context drift",dimension:"Consistency",onset:"Turn 3",turns:[["Student","My loop should repeat the beat four times, but it stops after one."],["AI Tutor","Check that your loop range includes four repetitions and that the beat is inside the loop."],["Student","I changed the range. Now the vocals start too early."],["AI Tutor","Remove the loop and place the vocal clip at measure 1."]]},
{id:"EDU-227",task:"Choose a sound for a student composition",priority:"High",signal:"Unsupported sound recommendation",dimension:"Helpfulness",onset:"Turn 2",turns:[["Student","Can you suggest a soft guitar sound from the library?"],["AI Tutor","Try ACOUSTIC_GUITAR_DREAM_07."],["Student","I cannot find that sound."],["AI Tutor","It may be available in another version of the library."]]},
{id:"EDU-091",task:"Explain variables to a novice programmer",priority:"Medium",signal:"Learner-level mismatch",dimension:"Context alignment",onset:"Turn 1",turns:[["Student","What is a variable? I just started coding."],["AI Tutor","A variable is a symbolic reference bound to a mutable value in memory."],["Student","Can you explain that more simply?"],["AI Tutor","Think of it as a labeled box that stores information you can use later."]]}
];
let stage="ready",analysisStep=0,selected="EDU-184",analysisTimer=null;const decisions={};
const processSteps=[["Build trajectories","Group 1,400 turns into 320 ordered tutoring sessions."],["Apply dimensions & criteria","Score Reasoning Transparency, Helpfulness, Consistency, and Context Alignment using education-specific criteria."],["Run automated screening","Combine rule-based checks, rubric-guided LLM judges, and threshold ranking to flag likely concerns."],["Predict trajectory risk","Estimate likely onset, persistence, and recovery, then prioritize sessions for structured human review."]];
const esc=v=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
export function renderProductDemo(root){
 const item=sessions.find(x=>x.id===selected);
 root.innerHTML=`<div class="page product-demo-page"><header class="page-header"><div><span class="eyebrow">Activity 3 · Product Demo</span><h1>Analyze Educational AI interactions at scale</h1><p>Screen multi-turn tutoring sessions, complete a structured human review, and turn confirmed findings into reusable evaluation signals.</p></div><span class="demo-badge">Interactive prototype</span></header>
 <section class="synthetic-banner"><b>Synthetic Educational AI Dataset</b><span>320 tutoring sessions · 1,400 interaction turns</span><small>Generated for demonstration. Contains no real student data.</small></section>
 ${stage==="ready"?`<section class="card demo-launch"><span class="eyebrow">Large-scale behavioral QA</span><h2>Find sessions that need human attention</h2><p>This prototype applies predefined RHCA behavioral signals. Flagged sessions are suggestions for review, not confirmed failures.</p><div class="demo-pipeline"><span>Interaction logs</span><b>→</b><span>Automated screening</span><b>→</b><span>Structured human review</span><b>→</b><span>Human-confirmed signals</span></div><div class="method-preview"><article><span>Dimensions</span><b>R · H · C · A</b><small>Four shared behavioral dimensions</small></article><article><span>Criteria</span><b>Education-specific</b><small>Context, evidence, and rating anchors</small></article><article><span>Automated screening</span><b>Hybrid evaluation</b><small>Rules + rubric-guided LLM judges</small></article><article><span>Risk prediction</span><b>Trajectory-level</b><small>Onset · persistence · recovery</small></article></div><button id="runDemoAnalysis" class="button primary">Run Behavioral Analysis</button></section>`:stage==="analyzing"?`<section class="card analysis-process"><div class="analysis-process-head"><div><span class="eyebrow">Analysis in progress</span><h2>Making the filtering process visible</h2><p>Each step shows what the prototype uses before it produces review suggestions.</p></div><b>${Math.min(analysisStep+1,4)} of 4</b></div><div class="analysis-progress"><i style="width:${Math.min((analysisStep+1)*25,100)}%"></i></div><div class="process-step-list">${processSteps.map(([title,detail],index)=>`<article class="${index<analysisStep?"complete":index===analysisStep?"active":""}"><b>${index<analysisStep?"✓":index+1}</b><span><strong>${title}</strong><small>${detail}</small></span></article>`).join("")}</div><section class="live-method"><div><span>Active dimensions</span><b>Reasoning Transparency · Helpfulness · Consistency · Context Alignment</b></div><div><span>Example criteria</span><b>Correct guidance · Tracks prior code · Fits learner level · Supports the stated goal</b></div><div><span>Screening methods</span><b>Rule-based checks · Rubric-guided LLM judges · Threshold ranking</b></div><div><span>Risk output</span><b>Likely concern · Onset turn · Persistence · Recovery probability</b></div></section></section>`:
 `<div class="results-toolbar"><div><span class="eyebrow">Analysis complete</span><b>47 sessions suggested for human review</b></div><button id="restartDemo" class="button secondary">Start Over</button></div><div class="demo-metrics"><article><span>Sessions analyzed</span><b>320</b><small>1,400 turns</small></article><article><span>Flagged for review</span><b>47</b><small>14.7% of sessions</small></article><article><span>High priority</span><b>12</b><small>Review first</small></article><article><span>Possible recovery</span><b>9</b><small>Improved later</small></article></div>
 <div class="analysis-layout"><section class="card flagged-list"><div class="section-title"><h2>Flagged sessions</h2><span>3 examples</span></div><p>Select a trajectory to inspect.</p>${sessions.map(x=>`<button class="flagged-session ${x.id===selected?"active":""}" data-session-id="${x.id}"><span><b>${x.id}</b><small>${esc(x.task)}</small></span><em>${esc(decisions[x.id]||x.signal)}</em></button>`).join("")}</section>
 <section class="card trajectory-review"><div class="section-title"><div><span class="eyebrow">${item.id} · ${item.dimension}</span><h2>${esc(item.task)}</h2></div><span class="priority">${item.priority}</span></div><div class="trajectory-summary"><span>Suggested signal <b>${item.signal}</b></span><span>Possible onset <b>${item.onset}</b></span><span>Risk prediction <b>${item.priority==="High"?"86%":"64%"}</b></span></div><div class="demo-transcript">${item.turns.map(([who,text],i)=>`<article class="${who==="Student"?"student":"assistant"}"><span>${who} · Turn ${Math.floor(i/2)+1}</span><p>${esc(text)}</p></article>`).join("")}</div><div class="structured-review-fields"><span><small>Dimension</small><b>${item.dimension}</b></span><span><small>Criterion</small><b>${item.signal}</b></span><span><small>Rating anchor</small><b>${item.priority==="High"?"1 · Needs attention":"2 · Partial"}</b></span><span><small>Evidence turns</small><b>${item.onset}–Turn 4</b></span><span><small>Persistence</small><b>${item.priority==="High"?"Likely":"Possible"}</b></span><span><small>Recovery</small><b>${item.id==="EDU-091"?"Observed":"Not observed"}</b></span></div><div class="human-review"><div><span class="eyebrow">Structured human review</span><h3>${decisions[item.id]?`Decision: ${decisions[item.id]}`:"Confirm, revise, or dismiss the suggestion"}</h3></div><div><button class="button primary" data-decision="Confirmed">Confirm</button><button class="button secondary" data-decision="Needs revision">Edit</button><button class="button ghost" data-decision="Dismissed">Dismiss</button></div></div></section></div>
 <section class="card downstream-panel"><div><span class="eyebrow">Human-confirmed evaluation signals</span><h2>Reuse review decisions</h2><p>Confirmed examples can support evaluation and continuous improvement.</p></div><div><span>Regression tests</span><span>Evaluation reports</span><span>Dataset review</span><span>Post-training signals</span></div></section><p class="prototype-note">Prototype screening illustrates rule-based checks, rubric-guided LLM judges, and trajectory risk scoring. LLM-judge outputs require structured human confirmation and may vary across models and prompts. No live student data is used.</p>`}</div>`;
 root.querySelector("#runDemoAnalysis")?.addEventListener("click",()=>{
  stage="analyzing";
  analysisStep=0;
  renderProductDemo(root);
  clearTimeout(analysisTimer);
  const advance=()=>{
    analysisStep+=1;
    if(analysisStep>=4){
      stage="results";
      renderProductDemo(root);
      return;
    }
    renderProductDemo(root);
    analysisTimer=setTimeout(advance,850);
  };
  analysisTimer=setTimeout(advance,850);
 });
 root.querySelector("#restartDemo")?.addEventListener("click",()=>{
  clearTimeout(analysisTimer);
  stage="ready";
  analysisStep=0;
  selected="EDU-184";
  Object.keys(decisions).forEach(key=>delete decisions[key]);
  renderProductDemo(root);
 });
 root.querySelectorAll("[data-session-id]").forEach(b=>b.onclick=()=>{selected=b.dataset.sessionId;renderProductDemo(root)});
 root.querySelectorAll("[data-decision]").forEach(b=>b.onclick=()=>{decisions[selected]=b.dataset.decision;renderProductDemo(root)});
}