const sessions=[
{id:"EDU-184",task:"Debug a loop in a music-coding project",priority:"High",signal:"Context drift",dimension:"Consistency",onset:"Turn 3",turns:[["Student","My loop should repeat the beat four times, but it stops after one."],["AI Tutor","Check that your loop range includes four repetitions and that the beat is inside the loop."],["Student","I changed the range. Now the vocals start too early."],["AI Tutor","Remove the loop and place the vocal clip at measure 1."]]},
{id:"EDU-227",task:"Choose a sound for a student composition",priority:"High",signal:"Unsupported sound recommendation",dimension:"Helpfulness",onset:"Turn 2",turns:[["Student","Can you suggest a soft guitar sound from the library?"],["AI Tutor","Try ACOUSTIC_GUITAR_DREAM_07."],["Student","I cannot find that sound."],["AI Tutor","It may be available in another version of the library."]]},
{id:"EDU-091",task:"Explain variables to a novice programmer",priority:"Medium",signal:"Learner-level mismatch",dimension:"Context alignment",onset:"Turn 1",turns:[["Student","What is a variable? I just started coding."],["AI Tutor","A variable is a symbolic reference bound to a mutable value in memory."],["Student","Can you explain that more simply?"],["AI Tutor","Think of it as a labeled box that stores information you can use later."]]}
];
let analyzed=false,selected="EDU-184";const decisions={};
const esc=v=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
export function renderProductDemo(root){
 const item=sessions.find(x=>x.id===selected);
 root.innerHTML=`<div class="page product-demo-page"><header class="page-header"><div><span class="eyebrow">Activity 3 · Product Demo</span><h1>Analyze Educational AI interactions at scale</h1><p>Filter multi-turn tutoring sessions, review likely behavioral concerns, and turn confirmed findings into reusable evaluation signals.</p></div><span class="demo-badge">Interactive prototype</span></header>
 <section class="synthetic-banner"><b>Synthetic Educational AI Dataset</b><span>320 tutoring sessions · 1,400 interaction turns</span><small>Generated for demonstration. Contains no real student data.</small></section>
 ${!analyzed?`<section class="card demo-launch"><span class="eyebrow">Large-scale behavioral QA</span><h2>Find sessions that need human attention</h2><p>This prototype applies predefined RHCA behavioral signals. Flagged sessions are suggestions for review, not confirmed failures.</p><div class="demo-pipeline"><span>Interaction logs</span><b>→</b><span>Auto-filter</span><b>→</b><span>Human review</span><b>→</b><span>Reusable signals</span></div><button id="runDemoAnalysis" class="button primary">Run Behavioral Analysis</button></section>`:
 `<div class="demo-metrics"><article><span>Sessions analyzed</span><b>320</b><small>1,400 turns</small></article><article><span>Flagged for review</span><b>47</b><small>14.7% of sessions</small></article><article><span>High priority</span><b>12</b><small>Review first</small></article><article><span>Possible recovery</span><b>9</b><small>Improved later</small></article></div>
 <div class="analysis-layout"><section class="card flagged-list"><div class="section-title"><h2>Flagged sessions</h2><span>3 examples</span></div><p>Select a trajectory to inspect.</p>${sessions.map(x=>`<button class="flagged-session ${x.id===selected?"active":""}" data-session-id="${x.id}"><span><b>${x.id}</b><small>${esc(x.task)}</small></span><em>${esc(decisions[x.id]||x.signal)}</em></button>`).join("")}</section>
 <section class="card trajectory-review"><div class="section-title"><div><span class="eyebrow">${item.id} · ${item.dimension}</span><h2>${esc(item.task)}</h2></div><span class="priority">${item.priority}</span></div><div class="trajectory-summary"><span>Suggested signal <b>${item.signal}</b></span><span>Possible onset <b>${item.onset}</b></span></div><div class="demo-transcript">${item.turns.map(([who,text],i)=>`<article class="${who==="Student"?"student":"assistant"}"><span>${who} · Turn ${Math.floor(i/2)+1}</span><p>${esc(text)}</p></article>`).join("")}</div><div class="human-review"><div><span class="eyebrow">Human review</span><h3>${decisions[item.id]?`Decision: ${decisions[item.id]}`:"Confirm, revise, or dismiss the suggestion"}</h3></div><div><button class="button primary" data-decision="Confirmed">Confirm</button><button class="button secondary" data-decision="Needs revision">Edit</button><button class="button ghost" data-decision="Dismissed">Dismiss</button></div></div></section></div>
 <section class="card downstream-panel"><div><span class="eyebrow">Human-confirmed outputs</span><h2>Reuse review decisions</h2><p>Confirmed examples can support evaluation and continuous improvement.</p></div><div><span>Regression tests</span><span>Evaluation reports</span><span>Dataset review</span><span>Post-training signals</span></div></section><p class="prototype-note">Prototype analysis uses predefined signals. No production model or live student data is used.</p>`}</div>`;
 root.querySelector("#runDemoAnalysis")?.addEventListener("click",()=>{analyzed=true;renderProductDemo(root)});
 root.querySelectorAll("[data-session-id]").forEach(b=>b.onclick=()=>{selected=b.dataset.sessionId;renderProductDemo(root)});
 root.querySelectorAll("[data-decision]").forEach(b=>b.onclick=()=>{decisions[selected]=b.dataset.decision;renderProductDemo(root)});
}